### ISSUE TITLE
Documentation about behavior when sleeping

### ISSUE THREAD

**Issue by ejsuncy** [wywywywy/tesla-prometheus-exporter#14]
Can you provide some documentation or a comment here about the behavior of this project for the following:

- What data is returned when a Tesla vehicle is asleep? Does it continue to return the latest known values (which may be old if the car has been sleeping for a while)? Or does it simply return null/zero data points? 
- Will the polling keep the vehicle awake?
- Does the code rate limit its requests?
- How does the code handle container restarts? Is there a way to mount a volume to hold the access token that gets refreshed?

I'm looking to deploy this to a home Kubernetes cluster and will occasionally need to do node maintenance, which will stop the container and restart it on another node.

**Comment by wywywywy** [comment]
Good idea. I'll put these into the README.

> What data is returned when a Tesla vehicle is asleep? Does it continue to return the latest known values (which may be old if the car has been sleeping for a while)? Or does it simply return null/zero data points?

I think I know the answers but let me double check first and get back to you.

> Will the polling keep the vehicle awake?

No if it detects that the car is sleeping, it will not wake the car up.

> Does the code rate limit its requests?

Requests to the Tesla API is configured via the interval parameter. Requests to the exporter from Prometheus is not rate limited - this should be a job for the ingress / load balancer if required.

> How does the code handle container restarts? Is there a way to mount a volume to hold the access token that gets refreshed?

It's a stateless app, so it handles restarts no problem at all. The refresh token should be configured as a ConfigMap or Secret and mapped in as an environment variable. No volume is required. I will provide an example k8s manifest.

**Comment by ejsuncy** [comment]
Thanks for your response. 
By this: 

> How does the code handle container restarts? Is there a way to mount a volume to hold the access token that gets refreshed?

I mean consider an instance running on Kubernetes. There's an access token mapped as an environment var. The code refreshes the access token several times over the next couple days. Now Kubernetes kills and restarts the pod (for a variety of reasons...node maintenance, for example). In the new pod instance, the original access token is again mounted as an env var, but it's not valid anymore and the app stops working.

If you don't want to support mapping in a Tesla account username & password and handle getting the initial access token, another solution might be to allow the app to read the initial access token from a file. This would allow me to write an initContainer that reads username & password from k8s secret store, uses them to get an access token, and writes the access token to a shared volume mounted to both the initContainer and the main app container. The main app container would then read in the access token and refresh it as needed. Upon killing and restarting the pod, the initContainer would again read username & password, fetch access token, and provide it as a file to the main container.

With the current setup, I don't see a way of having an initContainer set env vars on the main container...

If you don't have time to implement that, I'm happy to work on it on my fork and submit a PR when it's done.

What do you think?

**Comment by wywywywy** [comment]
> What data is returned when a Tesla vehicle is asleep? Does it continue to return the latest known values (which may be old if the car has been sleeping for a while)? Or does it simply return null/zero data points?

It does not wake the car up. Yes it does return last known value, and yes the data may be old but it shouldn't be too far out if the car is sleeping.

> Now Kubernetes kills and restarts the pod (for a variety of reasons...node maintenance, for example). In the new pod instance, the original access token is again mounted as an env var, but it's not valid anymore and the app stops working.

My refresh token is weeks old now and still not expired yet. It'd be nice to know exactly how long it lasts.

> If you don't have time to implement that, I'm happy to work on it on my fork and submit a PR when it's done.

You have no idea how happy that'd make me feel!!! :)

**Comment by ejsuncy** [comment]
I spent the weekend looking over the [authentication docs](https://github.com/timdorr/tesla-api) by @timdorr and it seems they are out of date. The tesla login screen now requires a captcha challenge and response, so for now it looks like we are stuck using the access_token.

**Comment by wywywywy** [comment]
Thanks for doing the research @ejsuncy
